%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
actor User as 職員
participant FE as フロントエンド
participant KN as コンポーネント  
User->>KN:ユーザーアイコンボタンを押下
KN-->>FE:ユーザーメニューの表示
User->>KN:ログアウトボタンの押下
KN-->>FE:【SC0001】ログイン画面への遷移
