---
config:
  theme: forest
---
sequenceDiagram
autonumber
actor User as 職員
participant FE as フロントエンド
participant KN as コンポーネント  
User->>KN:ユーザーアイコンボタンを押下
KN-->>FE:ユーザーメニューの表示
User->>KN:ユーザーメニュー以外の個所の押下
KN-->>FE:ユーザーメニューの非表示
