%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント
  participant BE as バックエンド   
  User->>FE:検査メニュー項目ボタンを押下
  FE-->>FE:押下したボタンの選択/非選択を切り替える
  FE-->>FE:選択されている検査メニュー項目情報を、リストに保持する
  