%%{init:{'theme':'forest'}}%%

sequenceDiagram
  actor stf as 職員
  participant fe as フロントエンド
  participant cmp as コンポーネント
  participant be as バックエンド

  autonumber
  break 
    stf ->> fe: [キャンセル]タップ
    fe ->>fe: 確認ダイアログ終了
  end
  stf ->>fe: [OK]タップ
  fe ->>fe: request body作成
  fe ->> be: AP1014_検査結果を登録する<br>[POST] /consult/{consultNumber}/results
  break statuscodeが200以外
    fe->>cmp: 【CP0015】共通ダイアログを呼び出す
    Note over fe,cmp: status=400 (Bad Request)<br>「回答登録の入力形式が間違っています。」
    Note over fe,cmp: status=403 (Forbidden)<br>「会場ロック中です。<br>管理者のみ更新可能です。」
    Note over fe,cmp: status=404 (NotFound)<br>「受診情報が存在しません。」
  end
  fe ->>fe: examMenuState(jotai)から次の検査メニューを取得
  alt 次の検査メニューがある場合
    fe->>fe: 【SC0007】検査内容確認画面に遷移<br>/examorder-confirm/{受診番号}?exammenuid={検査メニューID}
  else 次の検査メニューがない場合
    fe ->>fe: 【SC0006】受診番号入力画面に遷移<br>/consultnumber-input?consultnumber={直前の受診番号}
  end