/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WELLSHIP
 * WELLSHIPのバックエンドです。
 * OpenAPI spec version: v1
 */
export type PlaceScheduleGetTeamPlaceSchedulesParams = {
  date?: string;
  teamId?: string;
};

export type PlaceScheduleGetTeamsParams = {
  date?: string;
};

export type HomeMenuGetHomeMenuSettingsParams = {
  placeScheduleId?: string | null;
};

export type EquipmentGetEquipmentSettingsParams = {
  examMenuId?: number;
};

export type ConsultGetInputExamItemsExamineeParams = {
  /**
   * 検査メニューID
   */
  examMenuId?: number;
};

export type ConsultGetExamItemsExamineeParams = {
  examMenuId?: number;
};

/**
 * 職員
 */
export interface Staff {
  /** 職員ID */
  staffId?: string;
  /** 職員名 */
  staffName?: string;
}

/**
 * 進捗明細
 */
export interface ProgressDetail {
  /** 対象者数 */
  count?: number;
  /** 状態値 */
  status?: number;
  /** 状態名 */
  statusName?: string;
}

/**
 * 進捗状況
 */
export interface Progress {
  /** 進捗明細 */
  details?: ProgressDetail[];
  /** 検査項目ID */
  examItemId?: number;
  /** 検査項目名 */
  examItemName?: string;
}

/**
 * 会場日程の進捗状況
 */
export interface PlaceScheduleProgress {
  /** 健診日 */
  examDate?: string;
  /** 会場名 */
  placeName?: string;
  /** 会場日程ID */
  placeScheduleId?: string;
  /** 進捗状況 */
  progress?: Progress[];
}

/**
 * 会場ロック状態リクエストモデル
 */
export interface PlaceScheduleLockingRequest {
  /** 会場日程ID */
  placeScheduleId?: string;
  /** ロック状態 */
  placeScheduleLockingStatus?: number;
}

/**
 * 会場ロック状態
 */
export interface PlaceScheduleLocking {
  /** 健診日 */
  examDate?: string;
  /** 会場ID */
  placeId?: string;
  /** 会場名 */
  placeName?: string;
  /** 会場日程ID */
  placeScheduleId?: string;
  /** ロック状態 */
  placeScheduleLockingStatus?: number;
  /** 最終更新日時 */
  updatedAt?: string;
  /** 最終更新者 */
  updatedBy?: string;
}

/**
 * 会場日程の班リスト
 */
export interface PlaceSchedule {
  /** 会場ID */
  placeId?: string;
  /** 会場名 */
  placeName?: string;
  /** 会場日程ID */
  placeScheduleId?: string;
  /** 開始時刻（HH:mm形式） */
  startTime?: string;
}

/**
 * 班ごとの会場日程リスト
 */
export interface PlaceSchedulePlaces {
  /** 健診日 */
  examDate?: string;
  /** 会場日程リスト */
  placeSchedules?: PlaceSchedule[];
  /** 班ID */
  teamId?: string;
  /** 班名 */
  teamName?: string;
}

/**
 * 会場
 */
export interface Place2 {
  /** 会場ID */
  placeId?: string;
  /** 会場名 */
  placeName?: string;
}

/**
 * 会場日程の班
 */
export interface PlaceScheduleTeam {
  /** 会場リスト */
  places?: Place2[];
  /** 班ID */
  teamId?: string;
  /** 班名 */
  teamName?: string;
}

/**
 * 会場日程の班リスト
 */
export interface PlaceScheduleTeams {
  /** 班リスト */
  teams?: PlaceScheduleTeam[];
}

/**
 * 検査結果出力状況を未出力に戻すリクエストモデル
 */
export interface UndoIntegrationExportStatusRequest {
  /** 出力履歴ID */
  exportId?: string;
}

/**
 * 検査結果出力履歴
 */
export interface ExportHistory {
  /** 項目数 */
  dataCount?: number;
  /** 健診日 */
  examDate?: string;
  /** 出力日時 */
  exportedAt?: string;
  /** 出力者 */
  exportedBy?: string;
  /** 出力履歴ID */
  exportId?: string;
  /** 会場名 */
  placeName?: string;
  /** 会場日程ID */
  placeScheduleId?: string;
  /** ロック状態 */
  placeScheduleLockingStatus?: number;
}

/**
 * 検査結果出力履歴リスト
 */
export interface ExportHistoryList {
  /** 検査結果出力履歴リスト */
  exportHistories?: ExportHistory[];
}

/**
 * 検査結果出力のリクエスト
 */
export interface ResultExportRequest {
  /** 会場日程ID */
  placeScheduleId?: string;
}

/**
 * 連携対象検査結果明細
 */
export interface ExportDataDetail {
  /** 項目数 */
  count?: number;
  /** 状態値 */
  status?: number;
  /** 状態名 */
  statusName?: string;
}

/**
 * 連携対象検査結果
 */
export interface ExportData {
  /** 連携対象検査結果明細 */
  details?: ExportDataDetail[];
  /** 健診日 */
  examDate?: string;
  /** 会場名 */
  placeName?: string;
  /** 会場日程ID */
  placeScheduleId?: string;
  /** ロック状態 */
  placeScheduleLockingStatus?: number;
  /** 開始時刻 */
  startTime?: string;
}

/**
 * 連携対象検査結果リスト
 */
export interface ExportDataList {
  /** 連携対象検査結果リスト */
  exportData?: ExportData[];
}

/**
 * ホームメニュー
 */
export interface HomeMenu {
  /** 使用可能条件 */
  availableConditions?: string[];
  /** ホームメニュー名 */
  menuName?: string;
  /** 遷移パス */
  path?: string;
}

/**
 * ホームメニューグループ
 */
export interface HomeMenuGroup {
  /** ホームメニューグループ名 */
  groupName?: string;
  /** ホームメニュー */
  menus?: HomeMenu[];
}

/**
 * ホームメニューグループリスト
 */
export interface HomeMenuGroupList {
  /** ホームメニューグループリスト */
  homeMenuGroups?: HomeMenuGroup[];
  /**
   * 会場日程状況
   * @nullable
   */
  placeScheduleLockingStatus?: number | null;
  /** 職員のロール */
  staffRole?: number;
}

/**
 * 検査メニューリスト
 */
export interface ExamMenuList {
  /** 検査メニューリスト */
  examMenus?: ExamMenu[];
}

/**
 * 検査機器
 */
export interface Equipment {
  /** アプリ起動URL */
  appLaunchUrl?: string;
  /** 検査機器ID */
  equipmentId?: number;
  /** 検査機器名 */
  equipmentName?: string;
  /** 処理スクリプトURL */
  processingScriptUrl?: string;
}

/**
 * 検査機器リスト
 */
export interface EquipmentList {
  /** 検査機器リスト */
  equipments?: Equipment[];
}

/**
 * 検査結果検証結果情報
 */
export interface VerifyExamItems {
  /** 検査結果入力項目グループ */
  examItemGroups?: ExamItemGroup[];
}

/**
 * 検査結果の登録の検査項目明細リクエストモデル
 */
export interface ExamItemDetailRequest {
  /** 検査項目明細ID */
  examItemDetailId?: number;
  /** 値 */
  value?: string;
}

/**
 * 検査結果の登録の検査項目リクエストモデル
 */
export interface ResultRequest {
  /** 検査項目明細 */
  examItemDetails?: ExamItemDetailRequest[];
  /** 検査項目ID */
  examItemId?: number;
}

/**
 * 検査結果の登録のリクエストモデル
 */
export interface ResultsRequest {
  /** 検査メニューID */
  examMenuId?: number;
  /** 検査項目 */
  examResults?: ResultRequest[];
}

/**
 * 検査結果登録エラー
 */
export interface ExamRegistResult {
  /** エラー内容 */
  description?: string;
  /** エラーレベル */
  errorLevel?: number;
}

/**
 * 検査正常値範囲
 */
export interface ExamNormalValueRange {
  /** エラーレベル */
  errorLevel?: number;
  /** 最大値 */
  maxValue?: number;
  /** 最小値 */
  minValue?: number;
}

/**
 * 検査項目明細選択肢
 */
export interface ExamItemDetailOption {
  /** 選択肢コード */
  code?: string;
  /** 選択肢名称 */
  name?: string;
  /** 表示順 */
  orderNumber?: number;
}

/**
 * キーボード
 */
export interface Keyboard {
  /** キーボード種別 */
  keyboardType?: number;
  /** キーボード入力値 */
  values?: string[];
}

/**
 * 検査項目明細
 */
export interface ExamItemDetail {
  /**
   * 中止理由ID
   * @nullable
   */
  cancelReasonId?: number | null;
  /** 小数部有効桁数 */
  decimalLength?: number;
  /** 機器ラベル */
  equipmentLabel?: string;
  /** 検査項目明細ID */
  examItemDetailId?: number;
  /** 選択肢 */
  examItemDetailOptions?: ExamItemDetailOption[];
  /** 検査正常値範囲 */
  examNormalValueRanges?: ExamNormalValueRange[];
  /** 検査依頼が存在するか */
  hasOrder?: boolean;
  /** 整数部最大桁数 */
  integerLength?: number;
  /** キーボード */
  keyboard?: Keyboard;
  /** 検査項目明細名 */
  name?: string;
  /** 配置番号 */
  positionNumber?: number;
  /** 前回値 */
  prevValue?: string;
  /** 検査項目明細種別 */
  type?: number;
  /** 単位 */
  unit?: string;
  /** 今回値 */
  value?: string;
}

/**
 * 検査結果入力項目
 */
export interface InputExamItem {
  /** 検査項目明細 */
  examItemDetails?: ExamItemDetail[];
  /** 検査項目ID */
  examItemId?: number;
  /** 検査結果登録エラー */
  examRegistResults?: ExamRegistResult[];
  /** 検査項目名 */
  name?: string;
  /** 配置番号 */
  positionNumber?: number;
}

/**
 * 検査項目グループ
 */
export interface ExamItemGroup {
  /** 検査結果入力項目 */
  examItems?: InputExamItem[];
  /** 検査項目グループ種別 */
  type?: number;
}

/**
 * 検査結果入力画面 受診者情報
 */
export interface InputExamExaminee {
  /** 受診日年齢 */
  examDateAge?: number;
  /** カナ氏名 */
  kanaName?: string;
  /** 性別 */
  sex?: number;
  /** 受付番号 */
  ticketNumber?: string;
}

/**
 * 実施有無と中止理由のリクエストモデル
 */
export interface ExecutionRequest {
  /**
   * 中止理由ID
   * @nullable
   */
  cancelReasonId?: number | null;
  /** 検査項目ID */
  examItemId?: number;
  /** 検査実施するか */
  isPerforming?: boolean;
}

/**
 * 実施有無と中止理由を束ねたリクエストモデル
 */
export interface ExecutionsRequest {
  /** 検査項目ごとの実施有無と中止理由 */
  executions?: ExecutionRequest[];
}

/**
 * 検査実施判断ルールの結果
 */
export interface ExamDecisionResult {
  /** 説明 */
  description?: string;
  /** エラーレベル */
  errorLevel?: number;
}

/**
 * 実施検査状況
 */
export interface ExamDetail {
  /**
   * 中止理由ID
   * @nullable
   */
  cancelReasonId?: number | null;
  /** 検査項目ID */
  examItemId?: number;
  /** 検査項目名 */
  examItemName?: string;
  /** 検査依頼が存在するか */
  hasOrder?: boolean;
}

/**
 * 関連検査項目
 */
export interface RelatedExamItem {
  /** 検査項目名 */
  examItemName?: string;
  /** 検査結果 */
  examResult?: string;
}

/**
 * 検査結果入力情報
 */
export interface InputExamItems {
  /** 受診番号 */
  consultNumber?: string;
  /** 受診者情報 */
  examinee?: InputExamExaminee;
  /** 検査結果入力項目グループ */
  examItemGroups?: ExamItemGroup[];
  /** 関連検査項目 */
  relatedExamItems?: RelatedExamItem[];
}

/**
 * 受診者情報
 */
export interface Examinee {
  /** 生年月日 */
  birthdate?: string;
  /** 受診日年齢 */
  examDateAge?: number;
  /** カナ氏名 */
  kanaName?: string;
  /** 氏名 */
  name?: string;
  /** 事業所名 */
  organizations?: string[];
  /** 同姓同名アラート */
  sameNameAlert?: boolean;
  /** 性別 */
  sex?: number;
  /** 受付番号 */
  ticketNumber?: string;
}

/**
 * 検査メニュー
 */
export interface ExamMenu {
  /** 検査メニューID */
  examMenuId?: number;
  /** 検査メニュー名 */
  examMenuName?: string;
}

/**
 * 検査内容
 */
export interface ExamContent {
  /** 特記事項 */
  consultName?: string;
  /** 受診番号 */
  consultNumber?: string;
  /** 検査実施判断結果 */
  examDecisionResults?: ExamDecisionResult[];
  /** 受診者情報 */
  examinee?: Examinee;
  /** 実施検査項目 */
  examItems?: ExamDetail[];
  /** 検査実施判断 */
  isComplete?: boolean;
  /** 関連検査項目 */
  relatedExamItems?: RelatedExamItem[];
  /** 未実施検査項目 */
  unexaminedItems?: ExamMenu[];
}

/**
 * 未受診の検査項目リスト
 */
export interface UnexaminedMenuList {
  /** 受診ID */
  consultId?: string;
  /** 受診者ID */
  examineeId?: string;
  /** 受診者名 */
  examineeName?: string;
  /** 未受診の検査メニューリスト */
  unexaminedMenus?: ExamMenu[];
}

/**
 * 受診番号検証用リクエストモデル
 */
export interface ConsultNumberRequest {
  /** 受診番号 */
  consultNumber?: string;
}

/**
 * 中止理由
 */
export interface CancelReason {
  /** 中止理由ID */
  cancelReasonId?: number;
  /** 中止理由名 */
  cancelReasonName?: string;
  /** 検査項目ID */
  examItemId?: number;
}

/**
 * 中止理由リスト
 */
export interface CancelReasonList {
  /** 中止理由リスト */
  cancelReasons?: CancelReason[];
}

/**
 * アクセストークンをリフレッシュするためのリクエスト
 */
export interface AccessTokenRefreshRequest {
  /** アクセストークン */
  token?: string;
}

/**
 * 職員ログインのリクエストモデル
 */
export interface StaffLoginRequest {
  /** 職員のログインID */
  loginId?: string;
  /** パスワード */
  password?: string;
}

export interface ProblemDetails {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
  [key: string]: unknown | null;
}

/**
 * 職員ログインのレスポンスモデル
 */
export interface StaffLoginResponse {
  /** トークン */
  token?: string;
}

/**
 * 基準パターン
 */
export interface Threshold {
  /** 基準パターンコード */
  code?: string;
  /** エラーオブジェクトに登録する入力項目Noなど */
  inputNote?: string;
  /** 基準パターン名 */
  name?: string;
}

/**
 * 班
 */
export interface Team {
  /** 班コード */
  code?: string;
  /** エラーオブジェクトに登録する入力項目Noなど */
  inputNote?: string;
  /** 班名 */
  name?: string;
}

/**
 * 会場
 */
export interface Place {
  /** 会場コード */
  code?: string;
  /** エラーオブジェクトに登録する入力項目Noなど */
  inputNote?: string;
  /** 会場名 */
  name?: string;
}
