%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP1001】検査項目グループ_検査：血圧2回を呼び出す
  break 引数examItemsのpositionNumberが「1」と「2」の要素のexamItemDetailsの中にpositionNumberが「1」と「2」両方のexamItemDetailが無い場合
        KN->>FE:【CP1001】検査項目グループ_検査：血圧2回を表示しない
    end
  loop examItemsの要素を繰り返し処理
  alt cancelReasonIdが存在する場合 or hasOrderがfalseの場合
  KN->>KN:グレーアウトして表示
  end
  alt 引数.検査項目情報にexamRegistResultsが存在する場合
  KN->>KN:エラーメッセージを表示
  end
  alt 引数.登録ボタンフラグがtrueの場合
  KN->>KN:必須バリデーションチェック
  end
  KN->>KN:固有バリデーションチェック
  alt バリデーションチェックでエラーあり
  KN->>KN:エラーメッセージを表示  
  end
  KN->>KN:各パラメータの表示
  end
  KN-->>FE:【CP1001】検査項目グループ_検査：数値を返す