---
config:
  theme: forest
---
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP1013】検査項目グループ_検査：視力を呼び出す
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP1013】検査項目グループ_検査：視力を返す