services:
  postgres:
    image: postgres:16.3
    container_name: wellship-db
    restart: always
    ports:
      - "15433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p@ssw0rd"
      POSTGRES_DB: "postgres"
      PGPASSWORD: "p@ssw0rd"
