%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント 
  participant RG as ログイン制御
  participant BE as バックエンド   
  User->>FE:予約No.入力画面に遷移
  FE->>RG:ログイン有無確認
   note over FE,RG:共通処理
  RG-->>FE:ログイン有無を返す
  alt ログイン未
  FE->>User:ログイン用ポップアップ等の表示
  else ログイン済
  FE->>FE:zyotaiから会場名を取得
  FE->>FE:トークンからユーザー名を取得
  FE->>KN:共有ヘッダーから情報を取得
  KN-->>FE:画面名等の情報を返す 
  FE->>KN:共有フッターから情報を取得
  KN-->>FE:画面名等の情報を返す
  alt 前回個人のクエリパラメータが存在する
  FE->>BE:AP005_未受診の健診メニュー取得<br>[GET] /consult/{reservationNo}/unexaminedMenus
  BE-->>FE:レスポンスを取得  
  alt httpステータスコードが200
  activate FE   
  FE->>FE:取得したデータを前回個人情報として表示処理
  FE-->>User:予約No.入力画面の表示
  note over User,FE:取得した情報を表示  
  deactivate FE  
  User->>FE:予約確認テキストボックスを押下
  else 400エラー or 500エラー
  FE->>User:エラーメッセージを表示
  end
  end
  activate FE
  FE->>KN:カスタムキーボードの情報を取得
  KN-->>FE:情報を返す
  FE-->>User:カスタムキーボードの表示
  deactivate FE 
  User->>FE:カスタムキーボードの確定ボタンを押下 or <br>バーコードリーダでの読み込み
  FE->FE:予約確認テキストボックスのバリデーションチェック
  alt バリデーションチェックでエラー
  FE-->>User:予約Noエラーポップアップを表示
  else バリデーションチェックでエラー無し
  FE->>BE:AP004_予約No存在確認<br>[POST] /consult/reservationNo/verify<br>リクエストボディーに値を入力
  BE-->>FE:レスポンスを取得
  alt httpステータスコードが200
  FE-->>User:次画面に遷移 
  else  400エラー 0r 500エラー
  FE-->>User:予約Noエラーポップアップを表示
  User->>FE:閉じるボタンを押下
  FE-->>User:予約Noエラーポップアップを閉じる
  end  
  end 
   end