= フロントエンド

== フレームワーク
https://remix.run/[Remix] +
※ https://remix.run/docs/en/main/guides/spa-mode[Remix SPA Mode]を使用

== 使用するライブラリ

[options="header"]
|===
|[green]#ライブラリ# | [green]#機能#
|https://react-hook-form.com/[React Hook Form] |フォーム管理
|https://zod.dev/[zod] |バリデーション
|https://jotai.org/[jotai] |状態管理
|https://mantine.dev/[Mantine] |UI
|https://tanstack.com/query/latest[TanStack Query] |データフェッチ(キャッシュ機能あり)
|https://date-fns.org/[date-fns] |日付操作
|https://axios-http.com/[axios] |PromiseベースのHTTPクライアント
|https://tabler.io/icons[Tabler icons]|アイコンライブラリ
|===

== ライブラリ等のバージョン

[options="header"]
|===
|[green]#ライブラリ#| [green]#バージョン#
|https://nodejs.jp/[Node.js]| 22.9.0
|https://ja.react.dev/[React]| 18.2.0
|https://remix.run/[Remix]| 2.12.1
|https://mantine.dev/[Mantine]| 7.12.0
|===

== ディレクトリ構造

[source]
.
└── ResultCollector/ <.>
    ├── app/
    │   ├── api <.>
    │   ├── components <.>
    │   ├── domain <.>
    │   ├── routes <.>
    │   └── utils <.>
    └── public <.>

<.> 設定ファイル(*.config)や環境変数(.env)はrootフォルダ直下に配置

<.> API呼び出しはTanStack Queryを使用 +
apiフォルダ内の資産はOpenAPI設計書から出力したもののみ格納する(手編集NG)

<.> コンポーネントはcomponentsフォルダ直下に格納する +
小分けが必要になればサブディレクトリを作成する

<.> 定数や共通のモデルはdomainフォルダに格納する

<.> 画面はroutesフォルダに格納する +
ファイル名はケバブケースとする

<.> 共通関数はutilsフォルダに格納する +
年齢計算とかaxiosのinterceptorなど

<.> ソース以外の資産(faviconや画像など)はpublicフォルダに格納する +
資産が多くなりそうな場合はサブディレクトリを検討する

== CSS

トライアルでは https://github.com/css-modules/css-modules[CSS Modules]を使用する +
CSSファイル(*.module.css)は `app/styles` フォルダに格納する +
画面単位でのCSS定義は使用しない想定 +
本開発では何を使用するかは以下の内容を基に再検討する

* トライアルでCSS Modulesを使用してみた使用感
* デザインチームから出てきたデザイン

== データ管理(作成中)
* 認証情報(JWT)に持たせる
** テナント情報
** ユーザー情報
*** ロールなどの権限も含みたい
* 画面間のパラメータで受け渡しする
** 対象者の情報
*** 予約No
** 検査中の項目
*** 検査項目コード
** 一覧で表示対象の項目
*** 検査項目コード
* 状態管理に持たせる
** 選択した班情報
** 選択した会場情報
*** 班情報・会場情報は過去のデータを修正したい場合にどうするかという問題がある
** 選択した検査項目
*** 1.身長 2.腹囲…のような情報
** 健診機関で実施する健診メニュー

TODO: 必要なパラメータは画面一覧から洗い出す

== エディター関連
文字コード:: UTF-8(BOMなし)
改行コード:: CRLF
コードフォーマッタ:: https://biomejs.dev/ja/[Biome]をトライアル使用する

== APIコール時の共通処理

**未作成** +
リトライ処理、共通のエラーハンドリングなどを実装する予定 +
リトライ条件については要検討 +
(ステータスコード、HTTPメソッドの種類での判断が可能か要調査)

== コンポーネント作成ルール

https://ja.react.dev/learn/your-first-component[初めてのコンポーネント(React公式)] +
https://qiita.com/yusuke2310/items/aae90a6fc475ad0cb329[【React】コンポーネントとは？Reactにおけるルール]

コンポーネントで扱うデータはコンポーネントに引数で渡されたデータのみとする +
引数の渡し方はpropsとする？分割代入とする？ +
https://qiita.com/cha_ayu418/items/7fe607bec2b4acf8b8d3[関数コンポーネントのpropsの渡し方と分割代入] 

コンポーネントは関数コンポーネントとクラスコンポーネントのどちらで作成する？ +
現在は関数コンポーネントのほうが主流っぽい？ +
https://choippo.com/react-component/[【React】コンポーネントの基本と使い方を初心者向けに解説！] +
https://www.twilio.com/ja-jp/blog/react-choose-functional-components-jp[React:関数コンポーネントとクラスコンポーネントの違い]

コンポーネントから呼び出し元の画面に値を返すときはコールバック関数を使用する +
https://qiita.com/aliceroot0678/items/e4eabcbe3f9f79cada55[React 子から親へ入力内容を渡す] +
https://qiita.com/282Haniwa/items/46c01c9a8e2acc130d89[いいから黙ってpropsのコールバックは`on`から始めておけ]

=== コールバック関数の定義について

##callbackHogehoge##のように関数名の頭に##callback##をつける。以降はキャメルケースとする。 +

[source,js,indent=4]
----
// 画面からコンポーネントを定義する例
const callbackConfirm = () => {}
<Hoge onConfirm={callbackConfirm} />
----


== メモ
* TanStack QueryでAPIキャッシュを行う
** https://zenn.dev/eviry/articles/9bb81136a8cde0[TanStack Queryを用いたキャッシュハンドリング入門]

* 未ログイン状態で直接URLを叩くなどしてログインが必要な画面に遷移してきた場合、ログイン画面に遷移する処理をどこで行うか
** 認証チェックだけの画面をコンポーネントとして作成し、認証が必要な画面についてはそのコンポーネントを読み込むようにする？ +
(SSRだとカスタムフックを作成して認証処理をroot.tsxから呼び出せばできるみたいだったけど、SPAだと認証チェックを実装した別レイアウトを読み込まないといけない)

実装例

app/components/secureLayout.tsx
[source,js,indent=4]
----
import { useNavigate } from "@remix-run/react";
import { useEffect } from "react";

export default function SecureLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigate = useNavigate();

  useEffect(() => {
    // 認証チェックを行う
    const token = localStorage.getItem("authToken");

    if (!token) {
      // 未ログイン状態の時はログイン画面に遷移する
      navigate("/login");
    }
  }, [navigate]);

  return <>{children}</>;
}
----
※ 認証チェックは仮

認証していないと使用できない画面.tsx
[source,js,indent=4]
----
import SecureLayout from "../components/secureLayout";

export default function Hoge() {
  return (
    <>
      <SecureLayout>
        <!-- ここにコードを記述 -->
      </SecureLayout>
    </>
  );
}
----

上記のように、認証が必要な画面で認証チェックを行うコンポーネントを読み込む +
認証が不要な画面(ログイン画面など)はこのコンポーネントを読み込まなければいい


== フロントエンド開発におけるルール

=== 設計時に留意すること
* エラー処理
** エラーメッセージは利用者がこの後どうすればいいのかがわかるよう設計する
** APIのステータスコードによってエラー内容を切り分ける
* 入力フォーム
** 必須項目・任意項目がわかるように設計する
** プレースホルダーを工夫する
** テキストボックスに属性をつける
** コンポーネントを使用する場合、バリデーションはコンポーネント内で行う(コンポーネント内でzodを使用する)
** コンポーネントを使用しない場合、バリデーションはzodを使用する

=== 実装時に留意すること
* TypeScriptを使用する
** 警告を放置しないこと
* 日付の処理について
** date-fnsを使用する
* 各画面、コンポーネント内にCSSを直接記述しない
* URL組み立て時、文字列結合を使用せずURLオブジェクトを使用する
* 状態管理に格納するものは制限する(なんでもかんでも入れない)
