= フロントエンド

== フレームワーク
https://remix.run/[Remix] +
※ https://remix.run/docs/en/main/guides/spa-mode[Remix SPA Mode]を使用

== 使用するライブラリ

[options="header"]
|===
|[green]#ライブラリ# | [green]#機能#
|https://react-hook-form.com/[React Hook Form] |フォーム管理
|https://zod.dev/[zod] |バリデーション
|https://jotai.org/[jotai] |状態管理
|https://mantine.dev/[Mantine] |UI
|https://tanstack.com/query/latest[TanStack Query] |データフェッチ(キャッシュ機能あり)
|https://date-fns.org/[date-fns] |日付操作
|https://axios-http.com/[axios] |PromiseベースのHTTPクライアント
|===

== ライブラリ等のバージョン

[options="header"]
|===
|[green]#ライブラリ#| [green]#バージョン#
|https://nodejs.jp/[Node.js]| 22.9.0
|https://ja.react.dev/[React]| 18.2.0
|https://remix.run/[Remix]| 2.12.1
|https://mantine.dev/[Mantine]| 7.12.0
|===

== ディレクトリ構造

[source]
.
└── ResultCollector/ <.>
    ├── app/
    │   ├── api <.>
    │   ├── components <.>
    │   ├── domain <.>
    │   ├── routes <.>
    │   └── utils <.>
    └── public <.>

<.> 設定ファイル(*.config)や環境変数(.env)はrootフォルダ直下に配置

<.> API呼び出しはTanStack Queryを使用 +
apiフォルダ内の資産はOpenAPI設計書から出力したもののみ格納する(手編集NG)

<.> コンポーネントはcomponentsフォルダ直下に格納する +
小分けが必要になればサブディレクトリを作成する

<.> 定数や共通のモデルはdomainフォルダに格納する

<.> 画面はroutesフォルダに格納する +
ファイル名はケバブケースとする

<.> 共通関数はutilsフォルダに格納する +
年齢計算とかaxiosのinterceptorなど

<.> ソース以外の資産(faviconや画像など)はpublicフォルダに格納する +
資産が多くなりそうな場合はサブディレクトリを検討する

== CSS

トライアルでは https://github.com/css-modules/css-modules[CSS Modules]を使用する +
CSSファイル(*.module.css)は `app/styles` フォルダに格納する +
画面単位でのCSS定義は使用しない想定 +
本開発では何を使用するかは以下の内容を基に再検討する

* トライアルでCSS Modulesを使用してみた使用感
* デザインチームから出てきたデザイン

== データ管理(作成中)
* 認証情報(JWT)に持たせる
** テナント情報
** ユーザー情報
*** ロールなどの権限も含みたい
* 画面間のパラメータで受け渡しする
** 対象者の情報
*** 予約No
** 検査中の項目
*** 検査項目コード
** 一覧で表示対象の項目
*** 検査項目コード
* 状態管理に持たせる
** 選択した班情報
** 選択した会場情報
*** 班情報・会場情報は過去のデータを修正したい場合にどうするかという問題がある
** 選択した検査項目
*** 1.身長 2.腹囲…のような情報
** 健診機関で実施する健診メニュー

TODO: 必要なパラメータは画面一覧から洗い出す

== エディター関連
文字コード:: UTF-8(BOMなし)
改行コード:: CRLF
コードフォーマッタ:: https://biomejs.dev/ja/[Biome]をトライアル使用する

== メモ
* TanStack QueryでAPIキャッシュを行う
** https://zenn.dev/eviry/articles/9bb81136a8cde0[TanStack Queryを用いたキャッシュハンドリング入門]

* 未ログイン状態で直接URLを叩くなどしてログインが必要な画面に遷移してきた場合、ログイン画面に遷移する処理をどこで行うか
** 認証チェックだけの画面をコンポーネントとして作成し、認証が必要な画面についてはそのコンポーネントを読み込むようにする？ +
(SSRだとカスタムフックを作成して認証処理をroot.tsxから呼び出せばできるっぽかったけど、SPAだと認証チェックを実装した別レイアウトを読み込まないといけないっぽい)

実装例

.app/components/secureLayout.tsx
[source,js,indent=4]
----
import { useNavigate } from "@remix-run/react";
import { useEffect } from "react";

export default function SecureLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigate = useNavigate();

  useEffect(() => {
    // 認証チェックを行う
    const token = localStorage.getItem("authToken");

    if (!token) {
      navigate("/login");
    }
  }, [navigate]);

  return <>{children}</>;
}
----
※ 認証チェックは仮

.認証していないと使用できない画面.tsx
[source,js,indent=4]
----
import SecureLayout from "../components/secureLayout";

export default function Hoge() {
  return (
    <>
      <SecureLayout>
        <!-- ここにコードを記述 -->
      </SecureLayout>
    </>
  );
}
----

上記のように、認証が必要な画面で認証チェックを行うコンポーネントを読み込む +
認証が不要な画面(ログイン画面など)はこのコンポーネントを読み込まなければOK