---
config:
  theme: forest
---
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP0006】検査項目進捗を呼び出す
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP0006】検査項目進捗を返す