---
config:
  theme: forest
---
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント 
  participant BE as バックエンド   
  User->>FE:【SC0002】班選択画面に遷移
  FE->>FE:Jotaiから班ID、職員名を取得
  FE->>KN:【CP0001】共通ヘッダーを呼び出す
  FE->>BE:AP1003_班を取得する<br>[GET]/placeSchedules/teams/{操作日当日}
  BE-->>FE:レスポンスを取得
  
  alt httpステータスコードが200かつ取得データが1件以上
  loop 班情報毎に
  FE->>KN:見出しボタンを呼び出す
  end 
  else (200かつデータ件数が0件)
  FE-->>FE:エラーメッセージを表示 
  else 400エラー or 500エラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  FE-->>User:【SC0002】班選択画面の表示
  note over User,FE:取得した情報を表示
 