= ドメイン

ドメイン層の設計を示します。

値オブジェクトやエンティティなどは厳密に区別しません。できるだけオブジェクトに業務ロジックを凝集させることが目的です。

* 年齢
* 受診者
* 会場日程
* 受診
* 中止理由
* 検査機器
* ホームメニュー

== 列挙型

列挙型（Enum）で表現するものを一覧で整理します。

=== 性別

受診者の生物学的性別を表現するコード。国際規格であるISO 5218に則る。

* https://ja.wikipedia.org/wiki/ISO_5218[ISO 5218 - Wikipedia]
* https://qiita.com/aoshirobo/items/32deb45cb8c8b87d65a4[システムで「性別」の情報を扱う前に知っておくべきこと - Qiita]

----
enum Sex
{
    男 = 1,
    女 = 2
}
----

=== 対象性別

基準値などの設定に使用します。

[source,csharp]
----
enum TargetSex
{
    男 = 1,
    女 = 2,
    両方 = 3
}
----

=== 受診進捗状況

受診単位の進捗ステータスです。

[source,csharp]
----
enum ConsultProgressStatus
{
    来場待ち = 11,
    検査中 = 21,
    キャンセル = 41
}
----

=== 検査進捗状況

検査項目単位の進捗ステータスです。
データベースには持ちません。

[source,csharp]
----
enum ExamItemProgressStatus
{
    未実施 = 11,
    検査済み = 41,
    検査中止 = 51
}
----

=== 集計検査進捗状況

進捗画面で取り扱うステータスです。

[source,csharp]
----
enum AggregatedProgressStatus
{
    予定 = 11,
    来場 = 21,
    済 = 41,
    中止 = 51
}
----

=== 会場日程状況

会場ロックのステータスです。 

[source,csharp]
----
enum PlaceScheduleLockingStatus
{
    検査中 = 21,
    検査完了 = 31
}
----

=== 会場日程データ出力状況

会場日程単位のデータ出力ステータスです。 

[source,csharp]
----
enum PlaceScheduleResultExportStatus
{
    未出力 = 11,
    出力済み = 31,
    出力エラー = 41
}
----

=== 受診データ出力状況

受診単位のデータ出力ステータスです。

[source,csharp]
----
enum ConsultResultExportStatus
{
    未出力 = 11,
    出力保留 = 21,
    出力済み = 31
}
----

=== キーボード種別

ソフトウェアキーボードのタイプです。

[source,csharp]
----
enum KeyboardType
{
    テンキー = 1,
    選択肢 = 2
}
----

=== 検査項目グループ種別

コンポーネントを出し分けるためのタイプです。
ファーストユーザーで使用するものが決まり次第、値を振ります。

[source,csharp]
----
enum ExamItemGroupType
{
    単一数値,
    単一選択,
    尿検査,
    インクリメント,
    左右数値,
    左右選択,
    身体計測,
    血圧1,
    血圧2,
    血圧3,
    視力,
    聴力,
    通過
}
----

=== 検査項目明細種別

フロントエンドで入力や選択を出し分けるためのタイプです。
検査項目種別ごとに設定します。

[source,csharp]
----
enum ExamItemDetailType
{
    入力 = 1,
    選択 = 2,
    演算値 =3
}
----

=== 入力エラーレベル

入力した結果値に対するエラーを表示するときのレベルです。

[source,csharp]
----
enum InputErrorLevel
{
    正常 = 1,
    警告 = 2,
    異常 = 3
}
----

=== ロール

職員に対して付与する役割です。権限グループとして使います。

[source,csharp]
----
enum Role
{
    一般 = 10,
    管理者 = 20
}
----

== ルール発火条件種別

ルールの発火条件（トリガー）をまとめる種別です。

「検査結果相関ルール」と「検査実施判断ルール」で使用します。

[source,csharp]
----
enum RuleTriggerType
{
    ThresholdExceeded = 1,
    AllInputsEqual = 2
}
----

[options="header",cols="1,3,8"]
|===

|値
|名称
|条件式

| 1
| ThresholdExceeded
| `絶対値({入力2:数値} - {入力1:数値}) > {判定1:数値}`

| 2
| AllInputsNotEqual
| `同値ではない({入力1:文字列}, {入力1:文字列}, ... {入力N:文字列})`

|===

データ型は基本的に文字列で、四則演算が必要なトリガーでは文字列を数値型（decimal型で小数点可）としてパースして計算します。変数の1,2,Nはテーブルの変数番号（`variable_number`）カラムで昇順ソートしたときの配列インデックスです。

== データソース種別

検査項目明細の値を取得する際の設定です。

[source,csharp]
----
enum SourceType
{
    今回値 = 1,
    前回値 = 2
}
----

[NOTE]
====
「検査結果相関ルール」と「検査実施判断ルール」における今回値の扱い

今回値は「リクエスト値（保存前）」＞「データベース値（保存後）」の優先度で取得します。
フロントエンドから検証・登録するためにPOSTした場合はリクエスト値を使用して、保存済みの結果値をGETする場合はデータベース値を使用するというケースを想定しています。
====

[NOTE]
====
前回値の定義

受診に関連付いた過去の検査結果のうち、指定した受診.健診日に最も近い過去日の結果を前回値として取得します。
====
