%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP0009】ブース特記を呼び出す
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP0009】ブース特記を返却