---
config:
  theme: forest
---
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント 
  participant BE as バックエンド   
  User->>FE:受診番号確認テキストボックスを押下
  FE->>KN:【CP0012】数字キーボード(整数)を呼び出す
  KN->>FE:【CP0012】数字キーボード(整数)の値変更<br>数字ボタン押下 or AC押下
  FE-->>FE:渡された値を保存してテキストボックスに表示  
 
  KN->>FE:【CP0012】数字キーボード(整数)の確定ボタンを押下
  FE->>FE:受診番号確認テキストボックス<br>バリデーションチェック
  alt バリデーションチェックでエラーなし
  FE->>BE:AP1007_受診番号を検証する<br>[POST] /consult/consultNumber/verify
  BE-->>FE:レスポンスを取得
  
  alt httpステータスコードが200
  FE->>FE:【SC0007】検査内容確認画面に遷移
  else 400エラー or 500エラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  else バリデーションチェックでエラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す  
  end
  



 