%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント 
  participant BE as バックエンド   
  User->>FE:バーコードリーダーで読み込み
  FE->>FE:読み込んだ値を保存して受診番号確認テキストボックスに表示
  FE->>FE:受診番号確認テキストボックス<br>バリデーションチェック
  alt バリデーションチェックでエラーなし
  FE->>BE:AP1007_受診番号を検証する<br>[POST] /consult/consultNumber/verify
  BE-->>FE:レスポンスを取得
  alt httpステータスコードが200
  FE->>FE:【SC0007】検査内容確認画面に遷移
  else 400エラー or 500エラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  else バリデーションチェックでエラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  



 