%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント
  participant BE as バックエンド  
  User->>FE:【SC0020】検査結果出力履歴画面に遷移
  FE->>FE:Jotaiから職員名を取得 
  FE->>KN:【CP0001】共通ヘッダーを呼び出す
  FE->>KN:【CP0002】共通フッターを呼び出す
  FE->>BE:AP1020_検査結果の出力履歴を取得する<br>[GET]/integrations/examResults/exportHistory
  BE-->>FE:レスポンスを取得（出力履歴情報）
  alt httpステータスコードが200かつ取得データが1件以上
  loop テーブルに1行ずつ表示
  FE->>FE:取得した各パラメータを出力履歴情報として表示処理
  end
  else 200かつデータ件数が0件
  FE-->>User:エラーメッセージ（出力履歴情報）を表示
  else 400エラー or 500エラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  FE-->>User:【SC0020】検査結果出力履歴画面の表示
  note over User,FE:取得した情報を表示