%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント
  participant BE as バックエンド  
  User->>FE:未出力ボタンを押下
  FE-->>User:確認ダイアログを表示
  User->>FE:未出力確定ボタンを押下
  FE-->>FE:確認ダイアログを閉じる
  FE->>BE:AP1021_検査結果の連携状態を変更する<br>[PUT]/consult/{placeScheduleId}/integrationStatus
  alt httpステータスコードが200
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  else 400エラー or 500エラー
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  end
  User->>FE:戻るボタンを押下
  FE-->>FE:確認ダイアログを閉じる