
/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * WELLSHIP
 * WELLSHIPのバックエンドです。
 * OpenAPI spec version: v1
 */
export type PlaceScheduleGetTeamsParams = {
    date?: string;
    };
    
    /**
     * 会場
     */
    export interface Place {
      /** 会場ID */
      placeId?: number;
      /** 会場名 */
      placeName?: string;
    }
    
    /**
     * 会場日程の班
     */
    export interface PlaceScheduleTeam {
      /** 会場リスト */
      places?: Place[];
      /** 班ID */
      teamId?: number;
      /** 班名 */
      teamName?: string;
    }
    
    /**
     * 会場日程の班リスト
     */
    export interface PlaceScheduleTeams {
      /** 班リスト */
      teams?: PlaceScheduleTeam[];
    }
    
    /**
     * 予約No検証用リクエストモデル
     */
    export interface ReservationNoRequest {
      /** 予約No */
      reservationNo?: string;
    }
    
    export interface ProblemDetails {
      /** @nullable */
      detail?: string | null;
      /** @nullable */
      instance?: string | null;
      /** @nullable */
      status?: number | null;
      /** @nullable */
      title?: string | null;
      /** @nullable */
      type?: string | null;
      [key: string]: unknown | null;
    }