%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP0013】検査項目結果表示を呼び出す
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP0013】検査項目結果表示を返す
