```mermaid
%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor st as 職員
  participant fr as フロントエンド
  participant co as コンポーネント
  participant ba as バックエンド

  st ->> fr: 受信ボタン押下
  fr -->> st: 機器選択ダイアログを表示
```
