// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *WSGetSerialApiCodec(void);

@protocol WSSerialApi
/// 原生端实现的 open 方法，Flutter 端调用
/// @HostApi() 表示这是 Flutter 要调用 Native 的接口
/// SerialApi 是接口名（可以随便起）
/// open() 是要调用的方法名
///
/// @return `nil` only when `error != nil`.
- (nullable NSString *)openWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpWSSerialApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WSSerialApi> *_Nullable api);

extern void SetUpWSSerialApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WSSerialApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
