// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "serial_api.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface WSSerialApiPigeonCodecReader : FlutterStandardReader
@end
@implementation WSSerialApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface WSSerialApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation WSSerialApiPigeonCodecWriter
- (void)writeValue:(id)value {
  {
    [super writeValue:value];
  }
}
@end

@interface WSSerialApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation WSSerialApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[WSSerialApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[WSSerialApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *WSGetSerialApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    WSSerialApiPigeonCodecReaderWriter *readerWriter = [[WSSerialApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpWSSerialApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WSSerialApi> *api) {
  SetUpWSSerialApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWSSerialApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WSSerialApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  /// 原生端实现的 open 方法，Flutter 端调用
  /// @HostApi() 表示这是 Flutter 要调用 Native 的接口
  /// SerialApi 是接口名（可以随便起）
  /// open() 是要调用的方法名
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.wellship_serial_client.SerialApi.open", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WSGetSerialApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openWithError:)], @"WSSerialApi api (%@) doesn't respond to @selector(openWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api openWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
