/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WELLSHIP
 * WELLSHIPのバックエンドです。
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  ConsultNumberRequest,
  PlaceScheduleGetTeamsParams,
  PlaceScheduleTeams,
  ProblemDetails,
  UnexaminedItemList
} from './wellship.schemas'
import { customAxiosInstance } from './customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;



/**
 * @summary ログインする
 */
export const authenticationLogin = (
    version: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/login`, method: 'POST',
        responseType: 'blob'
    },
      );
    }
  


export const getAuthenticationLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authenticationLogin>>, TError,{version: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authenticationLogin>>, TError,{version: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authenticationLogin>>, {version: string}> = (props) => {
          const {version} = props ?? {};

          return  authenticationLogin(version,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthenticationLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authenticationLogin>>>
    
    export type AuthenticationLoginMutationError = unknown

    /**
 * @summary ログインする
 */
export const useAuthenticationLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authenticationLogin>>, TError,{version: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof authenticationLogin>>,
        TError,
        {version: string},
        TContext
      > => {

      const mutationOptions = getAuthenticationLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 中止理由を取得する
 */
export const cancelReasonGetCancelReasons = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/cancelReasons`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getCancelReasonGetCancelReasonsQueryKey = (version: string,) => {
    return [`/api/v${version}/cancelReasons`] as const;
    }

    
export const getCancelReasonGetCancelReasonsQueryOptions = <TData = Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCancelReasonGetCancelReasonsQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>> = ({ signal }) => cancelReasonGetCancelReasons(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData> & { queryKey: QueryKey }
}

export type CancelReasonGetCancelReasonsQueryResult = NonNullable<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>>
export type CancelReasonGetCancelReasonsQueryError = unknown


export function useCancelReasonGetCancelReasons<TData = Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCancelReasonGetCancelReasons<TData = Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useCancelReasonGetCancelReasons<TData = Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 中止理由を取得する
 */

export function useCancelReasonGetCancelReasons<TData = Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof cancelReasonGetCancelReasons>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCancelReasonGetCancelReasonsQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 受診番号の存在を確認する
 */
export const consultVerifyConsultNumber = (
    version: string,
    consultNumberRequest: ConsultNumberRequest,
 ) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/v${version}/consult/consultNumber/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: consultNumberRequest
    },
      );
    }
  


export const getConsultVerifyConsultNumberMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consultVerifyConsultNumber>>, TError,{version: string;data: ConsultNumberRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof consultVerifyConsultNumber>>, TError,{version: string;data: ConsultNumberRequest}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof consultVerifyConsultNumber>>, {version: string;data: ConsultNumberRequest}> = (props) => {
          const {version,data} = props ?? {};

          return  consultVerifyConsultNumber(version,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConsultVerifyConsultNumberMutationResult = NonNullable<Awaited<ReturnType<typeof consultVerifyConsultNumber>>>
    export type ConsultVerifyConsultNumberMutationBody = ConsultNumberRequest
    export type ConsultVerifyConsultNumberMutationError = ProblemDetails

    /**
 * @summary 受診番号の存在を確認する
 */
export const useConsultVerifyConsultNumber = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consultVerifyConsultNumber>>, TError,{version: string;data: ConsultNumberRequest}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof consultVerifyConsultNumber>>,
        TError,
        {version: string;data: ConsultNumberRequest},
        TContext
      > => {

      const mutationOptions = getConsultVerifyConsultNumberMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 未受診の検査項目を取得する
 */
export const consultGetUnexaminedItems = (
    version: string,
    consultNumber: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<UnexaminedItemList>(
      {url: `/api/v${version}/consult/${consultNumber}/unexaminedItems`, method: 'GET', signal
    },
      );
    }
  

export const getConsultGetUnexaminedItemsQueryKey = (version: string,
    consultNumber: string,) => {
    return [`/api/v${version}/consult/${consultNumber}/unexaminedItems`] as const;
    }

    
export const getConsultGetUnexaminedItemsQueryOptions = <TData = Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError = ProblemDetails>(version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsultGetUnexaminedItemsQueryKey(version,consultNumber);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consultGetUnexaminedItems>>> = ({ signal }) => consultGetUnexaminedItems(version,consultNumber, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && consultNumber), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData> & { queryKey: QueryKey }
}

export type ConsultGetUnexaminedItemsQueryResult = NonNullable<Awaited<ReturnType<typeof consultGetUnexaminedItems>>>
export type ConsultGetUnexaminedItemsQueryError = ProblemDetails


export function useConsultGetUnexaminedItems<TData = Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError = ProblemDetails>(
 version: string,
    consultNumber: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetUnexaminedItems>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetUnexaminedItems<TData = Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError = ProblemDetails>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetUnexaminedItems>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetUnexaminedItems<TData = Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError = ProblemDetails>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 未受診の検査項目を取得する
 */

export function useConsultGetUnexaminedItems<TData = Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError = ProblemDetails>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetUnexaminedItems>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getConsultGetUnexaminedItemsQueryOptions(version,consultNumber,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 簡易な受診者情報を取得する
 */
export const consultGetSimpleExaminee = (
    version: string,
    consultNumber: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/consult/${consultNumber}/simple`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getConsultGetSimpleExamineeQueryKey = (version: string,
    consultNumber: string,) => {
    return [`/api/v${version}/consult/${consultNumber}/simple`] as const;
    }

    
export const getConsultGetSimpleExamineeQueryOptions = <TData = Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError = unknown>(version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsultGetSimpleExamineeQueryKey(version,consultNumber);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consultGetSimpleExaminee>>> = ({ signal }) => consultGetSimpleExaminee(version,consultNumber, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && consultNumber), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData> & { queryKey: QueryKey }
}

export type ConsultGetSimpleExamineeQueryResult = NonNullable<Awaited<ReturnType<typeof consultGetSimpleExaminee>>>
export type ConsultGetSimpleExamineeQueryError = unknown


export function useConsultGetSimpleExaminee<TData = Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetSimpleExaminee>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetSimpleExaminee<TData = Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetSimpleExaminee>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetSimpleExaminee<TData = Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 簡易な受診者情報を取得する
 */

export function useConsultGetSimpleExaminee<TData = Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetSimpleExaminee>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getConsultGetSimpleExamineeQueryOptions(version,consultNumber,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 詳細な受診者情報を取得する
 */
export const consultGetDetailedExaminee = (
    version: string,
    consultNumber: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/consult/${consultNumber}/detail`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getConsultGetDetailedExamineeQueryKey = (version: string,
    consultNumber: string,) => {
    return [`/api/v${version}/consult/${consultNumber}/detail`] as const;
    }

    
export const getConsultGetDetailedExamineeQueryOptions = <TData = Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError = unknown>(version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConsultGetDetailedExamineeQueryKey(version,consultNumber);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof consultGetDetailedExaminee>>> = ({ signal }) => consultGetDetailedExaminee(version,consultNumber, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && consultNumber), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData> & { queryKey: QueryKey }
}

export type ConsultGetDetailedExamineeQueryResult = NonNullable<Awaited<ReturnType<typeof consultGetDetailedExaminee>>>
export type ConsultGetDetailedExamineeQueryError = unknown


export function useConsultGetDetailedExaminee<TData = Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetDetailedExaminee>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetDetailedExaminee<TData = Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof consultGetDetailedExaminee>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useConsultGetDetailedExaminee<TData = Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 詳細な受診者情報を取得する
 */

export function useConsultGetDetailedExaminee<TData = Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError = unknown>(
 version: string,
    consultNumber: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof consultGetDetailedExaminee>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getConsultGetDetailedExamineeQueryOptions(version,consultNumber,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 検査結果の連携状態を変更する
 */
export const consultChangeIntegrationStatus = (
    version: string,
    consultNumber: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/consult/${consultNumber}/integrationStatus`, method: 'PUT',
        responseType: 'blob'
    },
      );
    }
  


export const getConsultChangeIntegrationStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consultChangeIntegrationStatus>>, TError,{version: string;consultNumber: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof consultChangeIntegrationStatus>>, TError,{version: string;consultNumber: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof consultChangeIntegrationStatus>>, {version: string;consultNumber: string}> = (props) => {
          const {version,consultNumber} = props ?? {};

          return  consultChangeIntegrationStatus(version,consultNumber,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConsultChangeIntegrationStatusMutationResult = NonNullable<Awaited<ReturnType<typeof consultChangeIntegrationStatus>>>
    
    export type ConsultChangeIntegrationStatusMutationError = unknown

    /**
 * @summary 検査結果の連携状態を変更する
 */
export const useConsultChangeIntegrationStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof consultChangeIntegrationStatus>>, TError,{version: string;consultNumber: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof consultChangeIntegrationStatus>>,
        TError,
        {version: string;consultNumber: string},
        TContext
      > => {

      const mutationOptions = getConsultChangeIntegrationStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 機器連携設定を取得する
 */
export const equipmentGetEquipmentSettings = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/equipments`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getEquipmentGetEquipmentSettingsQueryKey = (version: string,) => {
    return [`/api/v${version}/equipments`] as const;
    }

    
export const getEquipmentGetEquipmentSettingsQueryOptions = <TData = Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEquipmentGetEquipmentSettingsQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>> = ({ signal }) => equipmentGetEquipmentSettings(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type EquipmentGetEquipmentSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>>
export type EquipmentGetEquipmentSettingsQueryError = unknown


export function useEquipmentGetEquipmentSettings<TData = Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useEquipmentGetEquipmentSettings<TData = Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useEquipmentGetEquipmentSettings<TData = Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 機器連携設定を取得する
 */

export function useEquipmentGetEquipmentSettings<TData = Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof equipmentGetEquipmentSettings>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getEquipmentGetEquipmentSettingsQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 検査メニュー一覧を取得する
 */
export const examMenuGetExamMenus = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/examMenus`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getExamMenuGetExamMenusQueryKey = (version: string,) => {
    return [`/api/v${version}/examMenus`] as const;
    }

    
export const getExamMenuGetExamMenusQueryOptions = <TData = Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExamMenuGetExamMenusQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof examMenuGetExamMenus>>> = ({ signal }) => examMenuGetExamMenus(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData> & { queryKey: QueryKey }
}

export type ExamMenuGetExamMenusQueryResult = NonNullable<Awaited<ReturnType<typeof examMenuGetExamMenus>>>
export type ExamMenuGetExamMenusQueryError = unknown


export function useExamMenuGetExamMenus<TData = Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof examMenuGetExamMenus>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useExamMenuGetExamMenus<TData = Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof examMenuGetExamMenus>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useExamMenuGetExamMenus<TData = Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 検査メニュー一覧を取得する
 */

export function useExamMenuGetExamMenus<TData = Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof examMenuGetExamMenus>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getExamMenuGetExamMenusQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ホームメニュー項目を取得する
 */
export const homeMenuGetHomeMenuSettings = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/homeMenus`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getHomeMenuGetHomeMenuSettingsQueryKey = (version: string,) => {
    return [`/api/v${version}/homeMenus`] as const;
    }

    
export const getHomeMenuGetHomeMenuSettingsQueryOptions = <TData = Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHomeMenuGetHomeMenuSettingsQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>> = ({ signal }) => homeMenuGetHomeMenuSettings(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type HomeMenuGetHomeMenuSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>>
export type HomeMenuGetHomeMenuSettingsQueryError = unknown


export function useHomeMenuGetHomeMenuSettings<TData = Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useHomeMenuGetHomeMenuSettings<TData = Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useHomeMenuGetHomeMenuSettings<TData = Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary ホームメニュー項目を取得する
 */

export function useHomeMenuGetHomeMenuSettings<TData = Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof homeMenuGetHomeMenuSettings>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHomeMenuGetHomeMenuSettingsQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 連携対象の検査結果を取得する
 */
export const integrationGetIntegrationResults = (
    version: string,
    placeScheduleId: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/integrations/results/${placeScheduleId}`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getIntegrationGetIntegrationResultsQueryKey = (version: string,
    placeScheduleId: string,) => {
    return [`/api/v${version}/integrations/results/${placeScheduleId}`] as const;
    }

    
export const getIntegrationGetIntegrationResultsQueryOptions = <TData = Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError = unknown>(version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIntegrationGetIntegrationResultsQueryKey(version,placeScheduleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof integrationGetIntegrationResults>>> = ({ signal }) => integrationGetIntegrationResults(version,placeScheduleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && placeScheduleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData> & { queryKey: QueryKey }
}

export type IntegrationGetIntegrationResultsQueryResult = NonNullable<Awaited<ReturnType<typeof integrationGetIntegrationResults>>>
export type IntegrationGetIntegrationResultsQueryError = unknown


export function useIntegrationGetIntegrationResults<TData = Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationGetIntegrationResults>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useIntegrationGetIntegrationResults<TData = Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationGetIntegrationResults>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useIntegrationGetIntegrationResults<TData = Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 連携対象の検査結果を取得する
 */

export function useIntegrationGetIntegrationResults<TData = Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetIntegrationResults>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getIntegrationGetIntegrationResultsQueryOptions(version,placeScheduleId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 連携用に検査結果を出力する
 */
export const integrationExportResults = (
    version: string,
    placeScheduleId: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/integrations/results/${placeScheduleId}/export`, method: 'POST',
        responseType: 'blob'
    },
      );
    }
  


export const getIntegrationExportResultsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationExportResults>>, TError,{version: string;placeScheduleId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof integrationExportResults>>, TError,{version: string;placeScheduleId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof integrationExportResults>>, {version: string;placeScheduleId: string}> = (props) => {
          const {version,placeScheduleId} = props ?? {};

          return  integrationExportResults(version,placeScheduleId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IntegrationExportResultsMutationResult = NonNullable<Awaited<ReturnType<typeof integrationExportResults>>>
    
    export type IntegrationExportResultsMutationError = unknown

    /**
 * @summary 連携用に検査結果を出力する
 */
export const useIntegrationExportResults = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof integrationExportResults>>, TError,{version: string;placeScheduleId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof integrationExportResults>>,
        TError,
        {version: string;placeScheduleId: string},
        TContext
      > => {

      const mutationOptions = getIntegrationExportResultsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 検査結果の出力履歴を取得する
 */
export const integrationGetExportHistory = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/integrations/results/exportedHistory`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getIntegrationGetExportHistoryQueryKey = (version: string,) => {
    return [`/api/v${version}/integrations/results/exportedHistory`] as const;
    }

    
export const getIntegrationGetExportHistoryQueryOptions = <TData = Awaited<ReturnType<typeof integrationGetExportHistory>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIntegrationGetExportHistoryQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof integrationGetExportHistory>>> = ({ signal }) => integrationGetExportHistory(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type IntegrationGetExportHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof integrationGetExportHistory>>>
export type IntegrationGetExportHistoryQueryError = unknown


export function useIntegrationGetExportHistory<TData = Awaited<ReturnType<typeof integrationGetExportHistory>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationGetExportHistory>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useIntegrationGetExportHistory<TData = Awaited<ReturnType<typeof integrationGetExportHistory>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof integrationGetExportHistory>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useIntegrationGetExportHistory<TData = Awaited<ReturnType<typeof integrationGetExportHistory>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 検査結果の出力履歴を取得する
 */

export function useIntegrationGetExportHistory<TData = Awaited<ReturnType<typeof integrationGetExportHistory>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof integrationGetExportHistory>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getIntegrationGetExportHistoryQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 日付を指定して班と会場のリストを取得する
 */
export const placeScheduleGetTeams = (
    version: string,
    params?: PlaceScheduleGetTeamsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<PlaceScheduleTeams>(
      {url: `/api/v${version}/placeSchedules/teams`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getPlaceScheduleGetTeamsQueryKey = (version: string,
    params?: PlaceScheduleGetTeamsParams,) => {
    return [`/api/v${version}/placeSchedules/teams`, ...(params ? [params]: [])] as const;
    }

    
export const getPlaceScheduleGetTeamsQueryOptions = <TData = Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError = ProblemDetails>(version: string,
    params?: PlaceScheduleGetTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlaceScheduleGetTeamsQueryKey(version,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof placeScheduleGetTeams>>> = ({ signal }) => placeScheduleGetTeams(version,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData> & { queryKey: QueryKey }
}

export type PlaceScheduleGetTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof placeScheduleGetTeams>>>
export type PlaceScheduleGetTeamsQueryError = ProblemDetails


export function usePlaceScheduleGetTeams<TData = Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError = ProblemDetails>(
 version: string,
    params: undefined |  PlaceScheduleGetTeamsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetTeams>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetTeams<TData = Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError = ProblemDetails>(
 version: string,
    params?: PlaceScheduleGetTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetTeams>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetTeams<TData = Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError = ProblemDetails>(
 version: string,
    params?: PlaceScheduleGetTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 日付を指定して班と会場のリストを取得する
 */

export function usePlaceScheduleGetTeams<TData = Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError = ProblemDetails>(
 version: string,
    params?: PlaceScheduleGetTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeams>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlaceScheduleGetTeamsQueryOptions(version,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 班を指定して会場日程を取得する
 */
export const placeScheduleGetTeamPlaceSchedules = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/placeSchedules/places`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getPlaceScheduleGetTeamPlaceSchedulesQueryKey = (version: string,) => {
    return [`/api/v${version}/placeSchedules/places`] as const;
    }

    
export const getPlaceScheduleGetTeamPlaceSchedulesQueryOptions = <TData = Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlaceScheduleGetTeamPlaceSchedulesQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>> = ({ signal }) => placeScheduleGetTeamPlaceSchedules(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData> & { queryKey: QueryKey }
}

export type PlaceScheduleGetTeamPlaceSchedulesQueryResult = NonNullable<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>>
export type PlaceScheduleGetTeamPlaceSchedulesQueryError = unknown


export function usePlaceScheduleGetTeamPlaceSchedules<TData = Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetTeamPlaceSchedules<TData = Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetTeamPlaceSchedules<TData = Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 班を指定して会場日程を取得する
 */

export function usePlaceScheduleGetTeamPlaceSchedules<TData = Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetTeamPlaceSchedules>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlaceScheduleGetTeamPlaceSchedulesQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 会場状況を取得する
 */
export const placeScheduleGetPlaceScheduleLockingStatus = (
    version: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/placeSchedules/placeScheduleLockingStatus`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getPlaceScheduleGetPlaceScheduleLockingStatusQueryKey = (version: string,) => {
    return [`/api/v${version}/placeSchedules/placeScheduleLockingStatus`] as const;
    }

    
export const getPlaceScheduleGetPlaceScheduleLockingStatusQueryOptions = <TData = Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError = unknown>(version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlaceScheduleGetPlaceScheduleLockingStatusQueryKey(version);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>> = ({ signal }) => placeScheduleGetPlaceScheduleLockingStatus(version, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type PlaceScheduleGetPlaceScheduleLockingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>>
export type PlaceScheduleGetPlaceScheduleLockingStatusQueryError = unknown


export function usePlaceScheduleGetPlaceScheduleLockingStatus<TData = Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError = unknown>(
 version: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetPlaceScheduleLockingStatus<TData = Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function usePlaceScheduleGetPlaceScheduleLockingStatus<TData = Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 会場状況を取得する
 */

export function usePlaceScheduleGetPlaceScheduleLockingStatus<TData = Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError = unknown>(
 version: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof placeScheduleGetPlaceScheduleLockingStatus>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPlaceScheduleGetPlaceScheduleLockingStatusQueryOptions(version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 会場状況を更新する
 */
export const placeScheduleUpdatePlaceScheduleLockingStatus = (
    version: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/placeSchedules/placeScheduleLockingStatus`, method: 'PUT',
        responseType: 'blob'
    },
      );
    }
  


export const getPlaceScheduleUpdatePlaceScheduleLockingStatusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>, TError,{version: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>, TError,{version: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>, {version: string}> = (props) => {
          const {version} = props ?? {};

          return  placeScheduleUpdatePlaceScheduleLockingStatus(version,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlaceScheduleUpdatePlaceScheduleLockingStatusMutationResult = NonNullable<Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>>
    
    export type PlaceScheduleUpdatePlaceScheduleLockingStatusMutationError = unknown

    /**
 * @summary 会場状況を更新する
 */
export const usePlaceScheduleUpdatePlaceScheduleLockingStatus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>, TError,{version: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof placeScheduleUpdatePlaceScheduleLockingStatus>>,
        TError,
        {version: string},
        TContext
      > => {

      const mutationOptions = getPlaceScheduleUpdatePlaceScheduleLockingStatusMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 進捗状況を取得する
 */
export const progressGetProgress = (
    version: string,
    placeScheduleId: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/progress/${placeScheduleId}`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getProgressGetProgressQueryKey = (version: string,
    placeScheduleId: string,) => {
    return [`/api/v${version}/progress/${placeScheduleId}`] as const;
    }

    
export const getProgressGetProgressQueryOptions = <TData = Awaited<ReturnType<typeof progressGetProgress>>, TError = unknown>(version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProgressGetProgressQueryKey(version,placeScheduleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof progressGetProgress>>> = ({ signal }) => progressGetProgress(version,placeScheduleId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && placeScheduleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData> & { queryKey: QueryKey }
}

export type ProgressGetProgressQueryResult = NonNullable<Awaited<ReturnType<typeof progressGetProgress>>>
export type ProgressGetProgressQueryError = unknown


export function useProgressGetProgress<TData = Awaited<ReturnType<typeof progressGetProgress>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof progressGetProgress>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useProgressGetProgress<TData = Awaited<ReturnType<typeof progressGetProgress>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof progressGetProgress>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useProgressGetProgress<TData = Awaited<ReturnType<typeof progressGetProgress>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 進捗状況を取得する
 */

export function useProgressGetProgress<TData = Awaited<ReturnType<typeof progressGetProgress>>, TError = unknown>(
 version: string,
    placeScheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof progressGetProgress>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProgressGetProgressQueryOptions(version,placeScheduleId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 検査結果を検証する
 */
export const resultVerifyResults = (
    version: string,
    consultId: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/consult/${consultId}/results/verify`, method: 'POST',
        responseType: 'blob'
    },
      );
    }
  


export const getResultVerifyResultsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resultVerifyResults>>, TError,{version: string;consultId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resultVerifyResults>>, TError,{version: string;consultId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resultVerifyResults>>, {version: string;consultId: string}> = (props) => {
          const {version,consultId} = props ?? {};

          return  resultVerifyResults(version,consultId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResultVerifyResultsMutationResult = NonNullable<Awaited<ReturnType<typeof resultVerifyResults>>>
    
    export type ResultVerifyResultsMutationError = unknown

    /**
 * @summary 検査結果を検証する
 */
export const useResultVerifyResults = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resultVerifyResults>>, TError,{version: string;consultId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof resultVerifyResults>>,
        TError,
        {version: string;consultId: string},
        TContext
      > => {

      const mutationOptions = getResultVerifyResultsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 検査結果を登録する
 */
export const resultRegisterResults = (
    version: string,
    consultId: string,
 ) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/consult/${consultId}/results`, method: 'POST',
        responseType: 'blob'
    },
      );
    }
  


export const getResultRegisterResultsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resultRegisterResults>>, TError,{version: string;consultId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resultRegisterResults>>, TError,{version: string;consultId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resultRegisterResults>>, {version: string;consultId: string}> = (props) => {
          const {version,consultId} = props ?? {};

          return  resultRegisterResults(version,consultId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ResultRegisterResultsMutationResult = NonNullable<Awaited<ReturnType<typeof resultRegisterResults>>>
    
    export type ResultRegisterResultsMutationError = unknown

    /**
 * @summary 検査結果を登録する
 */
export const useResultRegisterResults = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resultRegisterResults>>, TError,{version: string;consultId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof resultRegisterResults>>,
        TError,
        {version: string;consultId: string},
        TContext
      > => {

      const mutationOptions = getResultRegisterResultsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary 職員の情報を取得する
 */
export const staffGetStaff = (
    version: string,
    staffId: string,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<Blob>(
      {url: `/api/v${version}/staffs/${staffId}`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  

export const getStaffGetStaffQueryKey = (version: string,
    staffId: string,) => {
    return [`/api/v${version}/staffs/${staffId}`] as const;
    }

    
export const getStaffGetStaffQueryOptions = <TData = Awaited<ReturnType<typeof staffGetStaff>>, TError = unknown>(version: string,
    staffId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStaffGetStaffQueryKey(version,staffId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof staffGetStaff>>> = ({ signal }) => staffGetStaff(version,staffId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(version && staffId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData> & { queryKey: QueryKey }
}

export type StaffGetStaffQueryResult = NonNullable<Awaited<ReturnType<typeof staffGetStaff>>>
export type StaffGetStaffQueryError = unknown


export function useStaffGetStaff<TData = Awaited<ReturnType<typeof staffGetStaff>>, TError = unknown>(
 version: string,
    staffId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof staffGetStaff>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useStaffGetStaff<TData = Awaited<ReturnType<typeof staffGetStaff>>, TError = unknown>(
 version: string,
    staffId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof staffGetStaff>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useStaffGetStaff<TData = Awaited<ReturnType<typeof staffGetStaff>>, TError = unknown>(
 version: string,
    staffId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary 職員の情報を取得する
 */

export function useStaffGetStaff<TData = Awaited<ReturnType<typeof staffGetStaff>>, TError = unknown>(
 version: string,
    staffId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof staffGetStaff>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getStaffGetStaffQueryOptions(version,staffId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




