/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * WELLSHIP
 * WELLSHIPのバックエンドです。
 * OpenAPI spec version: v1
 */
import { faker } from "@faker-js/faker";
import { HttpResponse, delay, http } from "msw";
import type {
  CancelReasonList,
  EquipmentList,
  ExamContent,
  ExamMenuList,
  Examinee,
  ExportDataList,
  ExportHistoryList,
  HomeMenuGroupList,
  InputExamExaminee,
  InputExamItems,
  Keyboard,
  PlaceScheduleLocking,
  PlaceSchedulePlaces,
  PlaceScheduleProgress,
  PlaceScheduleTeams,
  Staff,
  StaffLoginResponse,
  UnexaminedMenuList,
  VerifyExamItems,
} from "../domain/wellship.schemas";

export const getAuthenticationLoginResponseMock = (
  overrideResponse: Partial<StaffLoginResponse> = {},
): StaffLoginResponse => ({
  token: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  ...overrideResponse,
});

export const getAuthenticationRefreshResponseMock = (
  overrideResponse: Partial<StaffLoginResponse> = {},
): StaffLoginResponse => ({
  token: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  ...overrideResponse,
});

export const getCancelReasonGetCancelReasonsResponseMock = (
  overrideResponse: Partial<CancelReasonList> = {},
): CancelReasonList => ({
  cancelReasons: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      cancelReasonId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      cancelReasonName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      examItemId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConsultGetUnexaminedMenusResponseMock = (
  overrideResponse: Partial<UnexaminedMenuList> = {},
): UnexaminedMenuList => ({
  consultId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  examineeId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  examineeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  unexaminedMenus: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examMenuId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examMenuName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConsultGetExamItemsExamineeResponseExamineeMock = (
  overrideResponse: Partial<Examinee> = {},
): Examinee => ({
  ...{
    birthdate: faker.helpers.arrayElement([
      faker.date.past().toISOString().split("T")[0],
      undefined,
    ]),
    examDateAge: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    kanaName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    organizations: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.word.sample()),
      undefined,
    ]),
    sameNameAlert: faker.helpers.arrayElement([
      faker.datatype.boolean(),
      undefined,
    ]),
    sex: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    ticketNumber: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  },
  ...overrideResponse,
});

export const getConsultGetExamItemsExamineeResponseMock = (
  overrideResponse: Partial<ExamContent> = {},
): ExamContent => ({
  consultName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  consultNumber: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  examDecisionResult: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.word.sample()),
    undefined,
  ]),
  examinee: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getConsultGetExamItemsExamineeResponseExamineeMock() },
    ]),
    undefined,
  ]),
  examItems: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      cancelReasonId: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          null,
        ]),
        undefined,
      ]),
      examItemId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examItemName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      hasOrder: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  isComplete: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  relatedExamItems: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItemName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      examResult: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  unexaminedItems: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examMenuId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examMenuName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConsultGetInputExamItemsExamineeResponseInputExamExamineeMock =
  (overrideResponse: Partial<InputExamExaminee> = {}): InputExamExaminee => ({
    ...{
      examDateAge: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      kanaName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      sex: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      ticketNumber: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    },
    ...overrideResponse,
  });

export const getConsultGetInputExamItemsExamineeResponseKeyboardMock = (
  overrideResponse: Partial<Keyboard> = {},
): Keyboard => ({
  ...{
    keyboardType: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    values: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.word.sample()),
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getConsultGetInputExamItemsExamineeResponseMock = (
  overrideResponse: Partial<InputExamItems> = {},
): InputExamItems => ({
  consultNumber: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  examinee: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getConsultGetInputExamItemsExamineeResponseInputExamExamineeMock() },
    ]),
    undefined,
  ]),
  examItemGroups: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          examItemDetails: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              cancelReasonId: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  null,
                ]),
                undefined,
              ]),
              decimalLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              equipmentLabel: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              examItemDetailId: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              examItemDetailOptions: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  code: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  orderNumber: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              examNormalValueRanges: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  errorLevel: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  maxValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  minValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              hasOrder: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              integerLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              keyboard: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  {
                    ...getConsultGetInputExamItemsExamineeResponseKeyboardMock(),
                  },
                ]),
                undefined,
              ]),
              name: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              positionNumber: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              prevValue: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              type: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              unit: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              value: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
            })),
            undefined,
          ]),
          examItemId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          examRegistResults: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              description: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              errorLevel: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
          positionNumber: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      type: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  relatedExamItems: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItemName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      examResult: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConsultValidatePriorExamMenusResponseInputExamExamineeMock = (
  overrideResponse: Partial<InputExamExaminee> = {},
): InputExamExaminee => ({
  ...{
    examDateAge: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    kanaName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    sex: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    ticketNumber: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  },
  ...overrideResponse,
});

export const getConsultValidatePriorExamMenusResponseKeyboardMock = (
  overrideResponse: Partial<Keyboard> = {},
): Keyboard => ({
  ...{
    keyboardType: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    values: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.word.sample()),
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getConsultValidatePriorExamMenusResponseMock = (
  overrideResponse: Partial<InputExamItems> = {},
): InputExamItems => ({
  consultNumber: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  examinee: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getConsultValidatePriorExamMenusResponseInputExamExamineeMock() },
    ]),
    undefined,
  ]),
  examItemGroups: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          examItemDetails: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              cancelReasonId: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  null,
                ]),
                undefined,
              ]),
              decimalLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              equipmentLabel: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              examItemDetailId: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              examItemDetailOptions: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  code: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  orderNumber: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              examNormalValueRanges: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  errorLevel: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  maxValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  minValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              hasOrder: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              integerLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              keyboard: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  { ...getConsultValidatePriorExamMenusResponseKeyboardMock() },
                ]),
                undefined,
              ]),
              name: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              positionNumber: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              prevValue: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              type: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              unit: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              value: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
            })),
            undefined,
          ]),
          examItemId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          examRegistResults: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              description: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              errorLevel: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
          positionNumber: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      type: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  relatedExamItems: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItemName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      examResult: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getConsultVerifyResultsResponseKeyboardMock = (
  overrideResponse: Partial<Keyboard> = {},
): Keyboard => ({
  ...{
    keyboardType: faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      undefined,
    ]),
    values: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => faker.word.sample()),
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getConsultVerifyResultsResponseMock = (
  overrideResponse: Partial<VerifyExamItems> = {},
): VerifyExamItems => ({
  errorLevel: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  examItemGroups: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          examItemDetails: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              cancelReasonId: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  faker.number.int({ min: undefined, max: undefined }),
                  null,
                ]),
                undefined,
              ]),
              decimalLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              equipmentLabel: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              examItemDetailId: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              examItemDetailOptions: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  code: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.word.sample(),
                    undefined,
                  ]),
                  orderNumber: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              examNormalValueRanges: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ min: 1, max: 10 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  errorLevel: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  maxValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                  minValue: faker.helpers.arrayElement([
                    faker.number.int({ min: undefined, max: undefined }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
              hasOrder: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              integerLength: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              keyboard: faker.helpers.arrayElement([
                faker.helpers.arrayElement([
                  { ...getConsultVerifyResultsResponseKeyboardMock() },
                ]),
                undefined,
              ]),
              name: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              positionNumber: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              prevValue: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              type: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
              unit: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              value: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
            })),
            undefined,
          ]),
          examItemId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          examRegistResults: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => ({
              description: faker.helpers.arrayElement([
                faker.word.sample(),
                undefined,
              ]),
              errorLevel: faker.helpers.arrayElement([
                faker.number.int({ min: undefined, max: undefined }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          name: faker.helpers.arrayElement([faker.word.sample(), undefined]),
          positionNumber: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      type: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getEquipmentGetEquipmentSettingsResponseMock = (
  overrideResponse: Partial<EquipmentList> = {},
): EquipmentList => ({
  equipments: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      appLaunchUrl: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      equipmentId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      equipmentName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      processingScriptUrl: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getExamMenuGetExamMenusResponseMock = (
  overrideResponse: Partial<ExamMenuList> = {},
): ExamMenuList => ({
  examMenus: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      examMenuId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examMenuName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getHomeMenuGetHomeMenuSettingsResponseMock = (
  overrideResponse: Partial<HomeMenuGroupList> = {},
): HomeMenuGroupList => ({
  homeMenuGroups: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      groupName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      menus: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          availableConditions: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1,
            ).map(() => faker.word.sample()),
            undefined,
          ]),
          menuName: faker.helpers.arrayElement([
            faker.word.sample(),
            undefined,
          ]),
          path: faker.helpers.arrayElement([faker.word.sample(), undefined]),
        })),
        undefined,
      ]),
    })),
    undefined,
  ]),
  placeScheduleLockingStatus: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  staffRole: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getIntegrationGetIntegrationResultsResponseMock = (
  overrideResponse: Partial<ExportDataList> = {},
): ExportDataList => ({
  exportData: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      details: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          count: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          status: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          statusName: faker.helpers.arrayElement([
            faker.word.sample(),
            undefined,
          ]),
        })),
        undefined,
      ]),
      examDate: faker.helpers.arrayElement([
        faker.date.past().toISOString().split("T")[0],
        undefined,
      ]),
      placeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      placeScheduleId: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      placeScheduleLockingStatus: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      startTime: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getIntegrationGetExportHistoryResponseMock = (
  overrideResponse: Partial<ExportHistoryList> = {},
): ExportHistoryList => ({
  exportHistories: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      dataCount: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examDate: faker.helpers.arrayElement([
        faker.date.past().toISOString().split("T")[0],
        undefined,
      ]),
      exportedAt: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
      ]),
      exportedBy: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      exportId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      placeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      placeScheduleId: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      placeScheduleLockingStatus: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPlaceScheduleGetTeamsResponseMock = (
  overrideResponse: Partial<PlaceScheduleTeams> = {},
): PlaceScheduleTeams => ({
  teams: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      places: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          placeId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
          placeName: faker.helpers.arrayElement([
            faker.word.sample(),
            undefined,
          ]),
        })),
        undefined,
      ]),
      teamId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      teamName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPlaceScheduleGetTeamPlaceSchedulesResponseMock = (
  overrideResponse: Partial<PlaceSchedulePlaces> = {},
): PlaceSchedulePlaces => ({
  examDate: faker.helpers.arrayElement([
    faker.date.past().toISOString().split("T")[0],
    undefined,
  ]),
  placeSchedules: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      placeId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      placeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
      placeScheduleId: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
      startTime: faker.helpers.arrayElement([faker.word.sample(), undefined]),
    })),
    undefined,
  ]),
  teamId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  teamName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  ...overrideResponse,
});

export const getPlaceScheduleGetPlaceScheduleLockingStatusResponseMock = (
  overrideResponse: Partial<PlaceScheduleLocking> = {},
): PlaceScheduleLocking => ({
  examDate: faker.helpers.arrayElement([
    faker.date.past().toISOString().split("T")[0],
    undefined,
  ]),
  placeId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  placeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  placeScheduleId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  placeScheduleLockingStatus: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  updatedAt: faker.helpers.arrayElement([
    `${faker.date.past().toISOString().split(".")[0]}Z`,
    undefined,
  ]),
  updatedBy: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  ...overrideResponse,
});

export const getProgressGetProgressResponseMock = (
  overrideResponse: Partial<PlaceScheduleProgress> = {},
): PlaceScheduleProgress => ({
  examDate: faker.helpers.arrayElement([
    faker.date.past().toISOString().split("T")[0],
    undefined,
  ]),
  placeName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  placeScheduleId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  progress: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      details: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          count: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          status: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          statusName: faker.helpers.arrayElement([
            faker.word.sample(),
            undefined,
          ]),
        })),
        undefined,
      ]),
      examItemId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      examItemName: faker.helpers.arrayElement([
        faker.word.sample(),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getStaffGetStaffResponseMock = (
  overrideResponse: Partial<Staff> = {},
): Staff => ({
  staffId: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  staffName: faker.helpers.arrayElement([faker.word.sample(), undefined]),
  ...overrideResponse,
});

export const getAuthenticationLoginMockHandler = (
  overrideResponse?:
    | StaffLoginResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<StaffLoginResponse> | StaffLoginResponse),
) => {
  return http.post("*/api/v:version/staff/login", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthenticationLoginResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getAuthenticationRefreshMockHandler = (
  overrideResponse?:
    | StaffLoginResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<StaffLoginResponse> | StaffLoginResponse),
) => {
  return http.post("*/api/v:version/staff/login/refresh", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAuthenticationRefreshResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getCancelReasonGetCancelReasonsMockHandler = (
  overrideResponse?:
    | CancelReasonList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CancelReasonList> | CancelReasonList),
) => {
  return http.get("*/api/v:version/cancelReasons", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCancelReasonGetCancelReasonsResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getConsultVerifyConsultNumberMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/consult/consultNumber/verify",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getConsultGetUnexaminedMenusMockHandler = (
  overrideResponse?:
    | UnexaminedMenuList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UnexaminedMenuList> | UnexaminedMenuList),
) => {
  return http.get(
    "*/api/v:version/consult/:consultNumber/unexaminedMenus",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConsultGetUnexaminedMenusResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getConsultGetExamItemsExamineeMockHandler = (
  overrideResponse?:
    | ExamContent
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExamContent> | ExamContent),
) => {
  return http.get(
    "*/api/v:version/consult/:consultNumber/examItems",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConsultGetExamItemsExamineeResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getConsultRegisterExecutionsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/consult/:consultNumber/executions",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getConsultGetInputExamItemsExamineeMockHandler = (
  overrideResponse?:
    | InputExamItems
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InputExamItems> | InputExamItems),
) => {
  return http.get(
    "*/api/v:version/consult/:consultNumber/inputExamItems",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConsultGetInputExamItemsExamineeResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getConsultValidatePriorExamMenusMockHandler = (
  overrideResponse?:
    | InputExamItems
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InputExamItems> | InputExamItems),
) => {
  return http.get(
    "*/api/v:version/consult/:consultNumber/prior/:currentExamId",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConsultValidatePriorExamMenusResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getConsultValidateCorrelationRuleMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/consult/:consultNumber/correlation",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getConsultRegisterResultsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/consult/:consultNumber/results",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getConsultVerifyResultsMockHandler = (
  overrideResponse?:
    | VerifyExamItems
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<VerifyExamItems> | VerifyExamItems),
) => {
  return http.post(
    "*/api/v:version/consult/:consultNumber/results/verify",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getConsultVerifyResultsResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getEquipmentGetEquipmentSettingsMockHandler = (
  overrideResponse?:
    | EquipmentList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<EquipmentList> | EquipmentList),
) => {
  return http.get("*/api/v:version/equipments", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getEquipmentGetEquipmentSettingsResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getExamMenuGetExamMenusMockHandler = (
  overrideResponse?:
    | ExamMenuList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExamMenuList> | ExamMenuList),
) => {
  return http.get("*/api/v:version/examMenus", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getExamMenuGetExamMenusResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getHealthCheckGetHealthMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.get("*/api/v:version/health/app", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getHealthCheckGetDeepHealthMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.get("*/api/v:version/health/database", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};

export const getHomeMenuGetHomeMenuSettingsMockHandler = (
  overrideResponse?:
    | HomeMenuGroupList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<HomeMenuGroupList> | HomeMenuGroupList),
) => {
  return http.get("*/api/v:version/homeMenus", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getHomeMenuGetHomeMenuSettingsResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getIntegrationGetIntegrationResultsMockHandler = (
  overrideResponse?:
    | ExportDataList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExportDataList> | ExportDataList),
) => {
  return http.get("*/api/v:version/integrations/examResults", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getIntegrationGetIntegrationResultsResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getIntegrationExportResultsMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/integrations/examResults/:placeScheduleId/export",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getIntegrationGetExportHistoryMockHandler = (
  overrideResponse?:
    | ExportHistoryList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ExportHistoryList> | ExportHistoryList),
) => {
  return http.get(
    "*/api/v:version/integrations/examResults/exportHistory",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getIntegrationGetExportHistoryResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getIntegrationUndoExportStatusMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.post(
    "*/api/v:version/integrations/examResults/undoExport",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getPlaceScheduleGetTeamsMockHandler = (
  overrideResponse?:
    | PlaceScheduleTeams
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlaceScheduleTeams> | PlaceScheduleTeams),
) => {
  return http.get("*/api/v:version/placeSchedules/teams", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPlaceScheduleGetTeamsResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPlaceScheduleGetTeamPlaceSchedulesMockHandler = (
  overrideResponse?:
    | PlaceSchedulePlaces
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlaceSchedulePlaces> | PlaceSchedulePlaces),
) => {
  return http.get("*/api/v:version/placeSchedules/places", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPlaceScheduleGetTeamPlaceSchedulesResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getPlaceScheduleGetPlaceScheduleLockingStatusMockHandler = (
  overrideResponse?:
    | PlaceScheduleLocking
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlaceScheduleLocking> | PlaceScheduleLocking),
) => {
  return http.get(
    "*/api/v:version/placeSchedules/:placeScheduleId/placeScheduleLockingStatus",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getPlaceScheduleGetPlaceScheduleLockingStatusResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getPlaceScheduleUpdatePlaceScheduleLockingStatusMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.put(
    "*/api/v:version/placeSchedules/:placeScheduleId/placeScheduleLockingStatus",
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
  );
};

export const getProgressGetProgressMockHandler = (
  overrideResponse?:
    | PlaceScheduleProgress
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PlaceScheduleProgress> | PlaceScheduleProgress),
) => {
  return http.get("*/api/v:version/progress/:placeScheduleId", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getProgressGetProgressResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getStaffGetStaffMockHandler = (
  overrideResponse?:
    | Staff
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Staff> | Staff),
) => {
  return http.get("*/api/v:version/staff/profile", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getStaffGetStaffResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getOrganizationTestInsertOrganizationMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.get("*/api/v:version/organization/insert", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};
export const getWellshipMock = () => [
  getAuthenticationLoginMockHandler(),
  getAuthenticationRefreshMockHandler(),
  getCancelReasonGetCancelReasonsMockHandler(),
  getConsultVerifyConsultNumberMockHandler(),
  getConsultGetUnexaminedMenusMockHandler(),
  getConsultGetExamItemsExamineeMockHandler(),
  getConsultRegisterExecutionsMockHandler(),
  getConsultGetInputExamItemsExamineeMockHandler(),
  getConsultValidatePriorExamMenusMockHandler(),
  getConsultValidateCorrelationRuleMockHandler(),
  getConsultRegisterResultsMockHandler(),
  getConsultVerifyResultsMockHandler(),
  getEquipmentGetEquipmentSettingsMockHandler(),
  getExamMenuGetExamMenusMockHandler(),
  getHealthCheckGetHealthMockHandler(),
  getHealthCheckGetDeepHealthMockHandler(),
  getHomeMenuGetHomeMenuSettingsMockHandler(),
  getIntegrationGetIntegrationResultsMockHandler(),
  getIntegrationExportResultsMockHandler(),
  getIntegrationGetExportHistoryMockHandler(),
  getIntegrationUndoExportStatusMockHandler(),
  getPlaceScheduleGetTeamsMockHandler(),
  getPlaceScheduleGetTeamPlaceSchedulesMockHandler(),
  getPlaceScheduleGetPlaceScheduleLockingStatusMockHandler(),
  getPlaceScheduleUpdatePlaceScheduleLockingStatusMockHandler(),
  getProgressGetProgressMockHandler(),
  getStaffGetStaffMockHandler(),
  getOrganizationTestInsertOrganizationMockHandler(),
];
