---
config:
  theme: forest
---
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  User->>KN:体重クリアボタンを押下
  KN->>KN:体重の値をクリア
  KN-->>FE:引数.体重変更イベントを呼び出す