%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  User->>KN:いずれかのクリアボタンを押下
  KN->>KN:対象の項目の値をクリア
  KN-->>KN:バリデーションチェック
  alt バリデーションチェックでエラー
  KN-->>KN:エラーメッセージを表示 
  end
  KN-->>FE:引数.変更イベントを呼び出す