---
config:
  theme: forest
---
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  User->>KN:身長クリアボタンを押下
  KN->>KN:身長の値をクリア
  KN-->>FE:引数.身長変更イベントを呼び出す