---
config:
  theme: forest
---
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント 
  FE->>KN:【CP0015】共通ダイアログを呼び出す
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP0015】共通ダイアログを返す