---
config:
  theme: forest
---
sequenceDiagram
autonumber
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP0013】キーボード(選択)を呼び出す
  KN->>KN:ボタンの表示
  KN-->>FE:【CP0013】キーボード(選択)を返却
