worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    server_tokens off;

    log_format json escape=json '{"time": "$time_iso8601",'
    '"host": "$remote_addr",'
    '"vhost": "$host",'
    '"user": "$remote_user",'
    '"status": "$status",'
    '"protocol": "$server_protocol",'
    '"method": "$request_method",'
    '"path": "$request_uri",'
    '"req": "$request",'
    '"size": "$body_bytes_sent",'
    '"apptime": "$upstream_response_time",'
    '"ua": "$http_user_agent",'
    '"forwardedfor": "$http_x_forwarded_for",'
    '"forwardedproto": "$http_x_forwarded_proto",'
    '"request_time": "$request_time",'
    '"referrer": "$http_referer"}';

    access_log /var/log/nginx/access.log json;

    index index.html index.htm;
    keepalive_timeout 300;
    gzip on;

    server {
        listen 80 default_server;
        server_name _;

        # Default charset setting
        charset utf-8;

        # Clickjacking protection
        add_header Content-Security-Policy "frame-ancestors 'none'";

        # Cache control
        add_header Cache-Control "no-store";

        location /ResultCollector/ {
            alias /usr/share/nginx/app/result-collector/;
            try_files $uri /ResultCollector/index.html;
        }

        location /ResultCollector/Equipments/ {
            alias /usr/share/nginx/app/result-collector-equipments/;
        }
    }
}
