%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  User->>KN:選択ボタンを押下
  KN->>KN:選択された選択ボタンをもとに値を更新
  alt onRegisterPressedがtrue
  KN->>KN:バリデーションチェック
  end
  KN-->>FE:引数.変更イベントを呼び出す