%%{init:{'theme':'forest'}}%%
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP1002】検査項目グループ_検査：選択を呼び出す
  break examItems.positionNumberが「1」の<br/>examItemDetails.positinoNumberが「1」の要素が存在しない場合
  KN-->>FE:【CP1002】検査項目グループ_検査：選択を表示しない
  end
  alt hasOrderがfalse または cancelReasonIdが存在する場合
  KN->>KN:グレーアウト（選択不可）して表示
  end
  alt 引数.検査項目情報にexamRegistResultsが存在する場合
  KN->>KN:エラーメッセージを表示
  end
  alt 引数.登録ボタンフラグがtrueの場合
  KN->>KN:バリデーションチェック
  alt バリデーションチェックでエラーあり
  KN->>KN:エラーメッセージを表示
  end
  end
  KN->>KN:各パラメータの表示
  KN-->>FE:【CP1002】検査項目グループ_検査：選択を返す