== AP1005_ホームメニュー項目を取得する

=== 概要

* ホーム画面の表示に必要なホームメニューを取得する
* ホームメニューの項目は設定したグループでグルーピングする
* グループとグループ内の項目は表示順の昇順でソートする
* メニューごとに使用可能条件を設定する。すべての条件を満たすメニューを利用できる。ただし空リストの場合は制限なく使用できる。
** `placeScheduleSelected`: 会場日程が選択済みである
** `placeScheduleUnlocked`: 会場ロックが解除されている
* 操作している職員のロール情報をレスポンスに含めて、フロントエンドでの画面制御に使用する

=== URI

[source]
----
[GET] /homeMenus
----

=== リクエストヘッダー

=== パスパラメータ

なし

=== クエリパラメータ

[cols="2,1,1,4,2" options="header"]
|===
|名称|必須|型|説明|具体例

|placeScheduleId
|No
|string
|会場日程ID。指定した場合は、会場ロック状況を取得して返却する。
|`f4c60b54-4275-4f3a-8abb-a666e773c181`

|===

=== リクエストボディ

なし

=== レスポンスボディ

[source,json]
----
{
  "homeMenuGroups": [
    {
      "groupName": "一般",
      "menus": [
        {
          "menuName": "進捗",
          "path": "progress",
          "availableConditions": [
            "placeScheduleSelected"
          ]
        }
      ]
    },
    {
      "groupName": "外部システム連携",
      "menus": [
        {
          "menuName": "健診結果出力",
          "path": "examResultsExport",
          "availableConditions": []
        },
        {
          "menuName": "健診結果出力履歴",
          "path": "examResultsExportHistory",
          "availableConditions": []
        }
      ]
    }
  ],
  "placeScheduleLockingStatus" : 21,
  "staffRole" : 10
}
----

=== ステータスコード

* 200 OK
* 401 Unauthorized
** JWT認証に失敗
* 404 NotFound
** （クエリパラメータに会場日程IDがある場合）指定した会場日程が存在しない


=== 仕様補足

ホームメニュー項目と使用可能条件、ロールによる使用可否は以下の通り。

[cols="2,2,2,2,1", options="header"]
|===
| ホームメニュー名 | パス | 会場ロックの解除が必要 | 会場日程の選択が必要 | 管理者のみ

| 検査メニュー選択
| exammenu-select
| 〇（ロック中表示）
| 〇
|

| 進捗
| progress
|
| 〇
|

| 会場ロック
| placeschedule-lock
| 〇（ロック中表示）
| 〇
| 〇

| 検査結果出力
| examresult-export
|
|
| 〇

| 検査結果出力履歴
| examresult-export-history
|
|  
| 〇

|===
