---
config:
  theme: forest
---
sequenceDiagram
autonumber
  #actor User as 職員
  participant FE as フロントエンド
  participant KN as コンポーネント  

  FE->>KN:【CP0005】見出しボタンを呼び出す
  KN->>KN:各パラメータの表示
  alt 引数.選択がtrue
  KN->>KN:【CP0005】見出しボタンの背景色を変更
  end
  KN-->>FE:【CP0005】見出しボタンを返す