---
title: "RION_AA_Series_screening_computer.js"
---
packet-beta
0: 'SP'
1: 'STX'
2-4: '"13/"'
5-14: 'SP'
15: '"/"'
16-25: 'SP'
26-27: '"//"'
28-32: '500Hz'
33-37: '1000Hz'
38-42: '2000Hz'
43-47: '4000Hz'
48: '"/"'
49-50: 'CRLF'
51: 'BCC'
52: 'ETX'